tap "koekeishiya/formulae"
tap "garethgeorge/homebrew-backrest-tap"

# Development tools
brew "gh"
brew "git" 
brew "gnupg"
brew "pinentry-mac"
brew "go"
brew "jq"
brew "openjdk"
brew "openjdk@21"
brew "maven"
brew "node"
brew "python@3.12"
brew "rust"
brew "tree"
brew "wget"
brew "curl"
brew "htop"
brew "fastfetch"
brew "fd"
brew "ripgrep"
brew "bat"
brew "eza"
brew "fzf"

# Window management
brew "koekeishiya/formulae/skhd"
brew "koekeishiya/formulae/yabai"

# Backup
brew "garethgeorge/backrest-tap/backrest"

# Applications
cask "1password"
cask "1password-cli"
cask "battery"
cask "chatgpt"
cask "claude"
cask "cursor"
cask "discord"
cask "flux-app"
cask "granola"
cask "karabiner-elements"
cask "minecraft"
cask "nordvpn"
cask "obsidian"
cask "warp"
cask "vlc"
cask "whatsapp"