tap "asmvik/formulae"
tap "garethgeorge/backrest-tap"
tap "stripe/stripe-cli"

# Development tools
brew "gh"
brew "git"
brew "gnupg"
brew "pinentry-mac"
brew "go"
brew "jq"
brew "mise"
brew "openjdk@21"
brew "maven"
brew "python@3.12"
brew "rustup"
brew "pyenv"
brew "pipx"
brew "uv"
brew "node"
brew "tree"
brew "wget"
brew "curl"
brew "htop"
brew "fastfetch"
brew "fd"
brew "ripgrep"
brew "bat"
brew "eza"
brew "fzf"
brew "xcodegen"
brew "xmlstarlet"
brew "speedtest-go"
brew "stripe/stripe-cli/stripe"
brew "awscli"
brew "sops"
brew "age"
brew "sccache"
brew "zizmor"
brew "starship"
brew "zoxide"
brew "atuin"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"

# Media
brew "ffmpeg"
brew "atomicparsley"
brew "poppler"
brew "sdl2_image"
brew "sdl2_mixer"
brew "sdl2_ttf"

# Window management
brew "asmvik/formulae/skhd"
brew "asmvik/formulae/yabai"

# Backup
brew "garethgeorge/backrest-tap/backrest"

# Applications
cask "1password"
cask "1password-cli"
cask "battery"
cask "caffeine"
cask "chatgpt"
cask "claude-code@latest"
cask "discord"
cask "docker-desktop"
cask "fastmail"
cask "figma"
cask "flux-app"
cask "ghostty"
cask "google-chrome"
cask "granola"
cask "grok-bot"
cask "karabiner-elements"
cask "linear"
cask "minecraft"
cask "nordvpn"
cask "obsidian"
cask "slack"
cask "warp"
cask "visual-studio-code"
cask "vlc"
cask "whatsapp"
cask "zoom"
cask "transmission"
cask "stremio"
cask "tailscale-app"

# Fonts
cask "font-jetbrains-mono-nerd-font"

# VS Code extensions
vscode "enkia.tokyo-night"
vscode "dbaeumer.vscode-eslint"
vscode "anthropic.claude-code"
vscode "bradlc.vscode-tailwindcss"
vscode "editorconfig.editorconfig"
vscode "golang.go"
vscode "hverlin.mise-vscode"
vscode "ms-playwright.playwright"
vscode "redhat.vscode-yaml"
vscode "tamasfe.even-better-toml"
vscode "vitest.explorer"
